### ISSUE TITLE
Navbar overlapping Heading and Radio button 

### ISSUE THREAD

**Issue by nitin-pandita** [nitin-pandita/Nitin-Fashionwear#23]
**Screenshots**
![Screenshot 2023-05-04 092412](https://user-images.githubusercontent.com/91310284/236109535-3b5c371b-87ed-495c-8ce1-0d0b5a9ddf57.png)

**Comment by naim16031988** [comment]
Probably the fixed navbar caused this . Assign it to me and i will take care

**Comment by nitin-pandita** [comment]
> Probably the fixed navbar caused this . Assign it to me and i will take care

all yours @naim16031988
