### ISSUE TITLE
Add links to the PartnerShip company links attached to them

### ISSUE THREAD

**Issue by nitin-pandita** [nitin-pandita/Nitin-Fashionwear#5]
![Screenshot 2023-04-30 231024](https://user-images.githubusercontent.com/91310284/235367937-730dd73d-c274-424b-b267-284a7921e9d2.png)

Make the links attached to them

**Comment by naim16031988** [comment]
Hi, I like your website. and I want to contribute to it. Can you please assign me this issue I think I can get it done.
thanks!

**Comment by nitin-pandita** [comment]
> Hi, I like your website. and I want to contribute to it. Can you please assign me this issue I think I can get it done. thanks!

sure @naim16031988 go for it
